### ISSUE TITLE
folded scalar misbehaves on indent-only lines

### ISSUE THREAD

**Issue by cajoz** [yaml/pyyaml#13]
Using PyYAML 3.11 in Python 2.7.6 on Ubuntu 14.04 LTS (64-bit)

When a folded scalar is specified (with chomp) with `>-`, a line containing only indentation causes the scalar to be parsed instead as a block scalar.

This example works as expected:
```yaml
abc: >-
  def
  ghi
```
which results in:
```python
{'abc': 'def ghi'}
```

This example returns the string as though `|-` was specified instead:
```yaml
abc: >-
  def
  
  ghi
```
which results in
```python
{'abc': 'abc\ndef'}
```

**Comment by ingydotnet** [comment]
This is the expected behavior. A blank line parses as a newline char. The chomp indicator has nothing to do with it. Chomp only affects the end of the scalar.

Also I think you meant 'literal scalar' when you said 'block scalar'. 'Block' refers to the indented style (as opposed to the JSON-like 'flow' style).

**Comment by ingydotnet** [comment]
ie Both literal and folded scalars are block forms.
