### ISSUE TITLE
Inconsistent rendering of aliases

### ISSUE THREAD

**Issue by TheFriendlyCoder** [yaml/pyyaml#151]
I've been experimenting with aliases and anchors lately, and have been digging into more detail regarding the specifics of how pyyaml handles the encoding/decoding (aka: loading/dumping) of these primitives. From what I understand there are certain limitations with the loading/dumping mechanics that prevent having a one-to-one mapping from the source data to the output format... (ie: aliases using the `<<:` extend operator aren't propagated to the output), which I can understand.

However, there is one unusual inconsistency I found during my testing. The rendering of aliases using the "extend" operator differ from those not using this operator. Here is a trivial example that illustrates:

```python
test = """
first: &first
    a: 1
    b: 2
    c: 3
second:
    *first
third:
    <<: *first
"""
print(yaml.dump(yaml.load(test), default_flow_style=False))
```

The output from this small script is as follows:

```
first: &id001
  a: 1
  b: 2
  c: 3
second: *id001
third:
  a: 1
  b: 2
  c: 3
```

There is also another subtle inconsistency with the way anchors are rendered as well. Anchors that are not referenced by at least one plain alias are omitted from the output. Consider the output generated when either the `second` or `third` nodes are omitted from my example above:

```
first: &id001
  a: 1
  b: 2
  c: 3
second: *id001
```

```
first:
  a: 1
  b: 2
  c: 3
third:
  a: 1
  b: 2
  c: 3
```

For consistency, I would have expected one of the following results from my first example:

```
first: &id001
  a: 1
  b: 2
  c: 3
second: *id001
third: *id001
```

```
first: &id001
  a: 1
  b: 2
  c: 3
second:
  a: 1
  b: 2
  c: 3
third:
  a: 1
  b: 2
  c: 3
```

In both cases the anchor is rendered consistently regardless of how it is referenced, regardless of whether it is referenced or not, and in both cases the aliases are rendered in a consistent manner.

Based on my crude understanding of the loading/dumping mechanics in pyyaml, the former example sounds like it is difficult if not impossible to implement, however perhaps it would be easy to implement a solution for the latter case. I think this would be less confusing to people trying to understand the nuances of the dumping / encoding logic for your library.

**Comment by TheFriendlyCoder** [comment]
I probably should also mention that I have only recently been delving more deeply into the YAML standards and pyyaml in particular, so if there's something here I'm totally overlooking just let me know.

Also, I was hoping to have clarified some of this behavior using the official YAML 1.1 specification but I couldn't find any mention anywhere in the spec for the `<<:` operator. Is this something particular to pyyaml or have I just overlooked it somewhere?

**Comment by perlpunk** [comment]
First I'd like to address the `<<`. This is not part of the official specification. It's called a "merge key". You can find it in the type repository here: http://yaml.org/type/ http://yaml.org/type/merge.html

Some frameworks have implemented this because this is indeed a convenient way to merge different dictionaries into one.

It's not called an "operator", but it indeed does an operation on loading. It merges the referenced mapping via `*alias` into another mapping.
During this operation, the original alias gets lost.
In the loaded data structure, there is no information left that this mapping was originally constructed using an alias.

It should become clear if you merge more than one mapping:
```
mapping1: &map1
  a: 1
  b: 2
mapping2: &map2
  c: 3
  d: 4
merged:
  <<: *map1
  <<: *map2
  # and some additional key value pairs
  e: 5
  f: 6
```

YAML is designed to load and dump data structures without loss of information.

The merge key is one of the (unofficial) types/tags that cannot preserve its original representation via aliases. (Only if you load the YAML document into a DOM preserving the input information.)

I hope this explains one of your questions.

> Anchors that are not referenced by at least one plain alias are omitted from the output.

Along with my explanation for the first question, I hope this behaviour becomes obvious.

If you have a data structure in python where one node is the *same* as another, meaning pointing to the same variable/data, then the dumper can recognize this and will

* add an anchor to the first occurrence
* output the second (and following) occurrences of this node as an alias

For that, the dumper has to prewalk the data structure in order to find if there are any repeated nodes.

If you load a YAML document into a data structure, information about anchors will get lost. If you have an anchor and never use the alias for it, there is no way to find out that an anchor was used. Since merge keys will lose the alias information, in your example the anchor will not appear in the output.

Hope that helps.

**Comment by TheFriendlyCoder** [comment]
Actually this does make a lot of sense. Thank you for the detailed explanation. In fact, since I posted my question earlier today I found one or two other cases where the yaml output was not as I had intuitively expected, however based on your explanation it would appear to be the intended result.

I guess from the way you describe it, in order to have more consistency between the input and output structure you'd need to preserve the original DOM, which I'm guessing is not currently being done by pyyaml and thus likely explains why it would be a significant amount of work to implement. :p

I think it would help avoid at least some confusion for users of your library if you were to invest the time to do so. Just something to consider as you continue to improve your library.

Thanks again.

**Comment by perlpunk** [comment]
Yeah, there's some stuff going on regarding YAML in general (we are building a test suite and tools around YAML).
Creating a DOM allowing you to manipulate YAML without losing any information is something I'd like to do, currently in Perl. I just began learning Python and try to help here where I can. =)

You might want to have a look at ruamel.yaml https://pypi.python.org/pypi/ruamel.yaml
It already provides roundtrip support (not preserving *everything*, but a lot, for example comments). I don't know how it handles merge keys in that regard, though.
