### ISSUE TITLE
Can't install pyyaml on RaspberryPi3 with python3

### ISSUE THREAD

**Issue by JosefProbst** [yaml/pyyaml#203]
`$ pip3 install pyyaml
Collecting pyyaml
  HTTP error 404 while getting https://www.piwheels.org/simple/pyyaml/PyYAML-4.1-cp35-cp35m-linux_armv7l.whl#sha256=a5b125a24244830d574ccfd8fab861198d2ffe491b73179ffd75abf78caee6ff (from https://www.piwheels.org/simple/pyyaml/)
  Could not install requirement pyyaml from https://www.piwheels.org/simple/pyyaml/PyYAML-4.1-cp35-cp35m-linux_armv7l.whl#sha256=a5b125a24244830d574ccfd8fab861198d2ffe491b73179ffd75abf78caee6ff because of error 404 Client Error: Not Found for url: https://www.piwheels.org/simple/pyyaml/PyYAML-4.1-cp35-cp35m-linux_armv7l.whl
Could not install requirement pyyaml from https://www.piwheels.org/simple/pyyaml/PyYAML-4.1-cp35-cp35m-linux_armv7l.whl#sha256=a5b125a24244830d574ccfd8fab861198d2ffe491b73179ffd75abf78caee6ff because of HTTP error 404 Client Error: Not Found for url: https://www.piwheels.org/simple/pyyaml/PyYAML-4.1-cp35-cp35m-linux_armv7l.whl for URL https://www.piwheels.org/simple/pyyaml/PyYAML-4.1-cp35-cp35m-linux_armv7l.whl#sha256=a5b125a24244830d574ccfd8fab861198d2ffe491b73179ffd75abf78caee6ff (from https://www.piwheels.org/simple/pyyaml/)
`

If I manuall open [https://www.piwheels.org/simple/pyyaml/](url) in my browser I can download every ".whl" but the 4.1 versions.

**Comment by NyanKiyoshi** [comment]
The 4.1 release was rolled back from PyPy (same as #201), that may explain the 404 errors. The latest release stable release is 3.13.

Try:
```
pip3 install pyyaml==3.13
```

**Comment by JosefProbst** [comment]
Thank you very much.
Installing version 3.13 works fine, but the thing is that I actually wanted to install [connexion](https://github.com/zalando/connexion). 
And although pip prints this:
`Collecting PyYAML>=3.11 (from connexion)`
I receive the same error.
But I guess this is nothing related to this issue anymore.

**Comment by nitzmahone** [comment]
Yeah, this seems like a bug/oversight on the part of whoever's redistributing the content. PyPI is the official source for packaged PyYAML bits, and deleting flawed releases is a fully supported operation there- not much we can do if an aggregator/redistributor can't handle that. The problem seems like it should go away whenever PyYAML 4.x drops, but meantime, seems like updating your requirements to add a `<4.0` constraint might also be a good plan until you've verified that whatever 4.x PyYAML looks like works with your application. Since this is not an issue that the PyYAML maintainers can do anything about, we're going to close it...
