### ISSUE TITLE
CVE-2017-18342 status

### ISSUE THREAD

**Issue by Jwomers** [yaml/pyyaml#207]
Hi, I am maintaining the safety database at PyUp, and I want to get clarity on which version of PyYAML fixes CVE-2017-18342? I know 4.1 was released and then retracted from PyPi. 

Does 3.13 fix CVE-2017-18342?

Thanks

**Comment by Kobold** [comment]
I haven't read the code, but it seems like 3.13 does not fix the CVE. The CVE was regarding the default-unsafe load method, and the change that fixed it (PR #74) was only merged in 4.1 onward, and has since been reverted from the main branch that 4.2 will be cut from.

Issue #193 has the most clarity on the release plan, but it's unclear what the timeline for having #74 (that is, a fix for the CVE) re-merged is. It might be a while before there's a fix for the CVE.

Thanks again for the work you do with PyUp @Jwomers — I would say this is a tricky situation for a safety database. The CVE is not a new thing, it merely got unsafe defaults that have been present since 2006 flagged. Users of PyYAML need to know that they're using a potentially dangerous package, but at the same time, this isn't shocking to anyone who has some familiarity with PyYAML and its sharp edges.

**Comment by ingydotnet** [comment]
@Kobold's assessment is spot on.

3.13 *only* addresses PyYAML working with Python 3.7.

The next release (almost certainly versioned as 4.2) has high hopes of including a fix for this issue.

**Comment by ljvmiranda921** [comment]
Hi, thanks for the pyyaml project. It has been very helpful!
Any updates on this bug?  Thank you very much for your time and effort!

**Comment by ingydotnet** [comment]
This issue is being addressed in the upcoming 5.1 release. 5.1b1 is out, and 5.1b3 [went out tonight](https://pypi.org/project/PyYAML/#history).

The PR that resolves this issue is https://github.com/yaml/pyyaml/pull/257

**Comment by FichteFoll** [comment]
I'm not sure if issueing a "warning" is enough to solve this issue immediately. While it's of course the correct step, this is only half of the way to fix the issue eventually.

**Comment by The-Compiler** [comment]
> I'm not sure if issueing a "warning" is enough to solve this issue immediately. While it's of course the correct step, this is only half of the way to fix the issue eventually.

Did you take a look at #257? From there:

> We added a new loader class called FullLoader, and we made it the default for
`load()`. This class is almost as complete for serialization as
UnsafeLoader/Loader, but it avoids arbitrary code execution. We don't expect it
will break any code in the wild.
>
> We still recommend that people choose SafeLoader for untrusted data, but
aribitrary code execution will no longer be possible using `yaml.load()` with
the default loader (FullLoader). FullLoader will instantiate objects of classes
that you have imported. Since object instantiation runs the class's constructor
code, that may be exploitable.

**Comment by FichteFoll** [comment]
My bad, I must have missed that `FullLoader` is the new default. This is perfectly fine, then. :+1:

**Comment by ingydotnet** [comment]
PyYAML 5.1 has been released.

https://pypi.org/project/PyYAML/5.1/

This release resolves CVE-2017-18342.

For latest details, see: https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation
