### ISSUE TITLE
Releases past 3.13 are not listed on pyyaml.org

### ISSUE THREAD

**Issue by akx** [yaml/pyyaml#277]
https://pyyaml.org/ only lists releases up to 3.13 (July 2018) on the front page and on https://pyyaml.org/wiki/PyYAML.

Should probably have the newer releases up there too, along with changelogs etc.

**Comment by typenil** [comment]
This would be helpful. I'm trying to upgrade from 3.13, and it would be helpful to know about any breaking changes we need to look out for.

**Comment by ngirard** [comment]
I've been hit by the same problem.

Because the documentation only mentioned version 3.13 I wrote `pyyaml = "==3.13"` in my Pipfile and got myself the old code.

I'd suggest the README file of this very Github repo is amended to make thinks clear(er), instead of just directing the reader to pyyaml.org/wiki.

Thanks in advance !

**Comment by Roesjka** [comment]
I concur the yaml developers should update their website asap otherwise Linux distros will be stuck updating the lot.

**Comment by perlpunk** [comment]
pyyaml.org is updated with the new version.
Documentation still needs to be updated with the new methods.

**Comment by ngirard** [comment]
Thanks @perlpunk !
