### ISSUE TITLE
Extra single quotation marks with datetime strings 

### ISSUE THREAD

**Issue by JoonaFinland** [yaml/pyyaml#302]
When dumping a dictionary with string values that are in the format of YYYY-MM-DD HH:MM:SS, the string has extra single quotes around it. 
```
import yaml
dict = {"Date1": '2019-12-22 11:11:11',
		"Date2": '2019-12-22 11:11.11',
		"Date3": '11:11:11',
		"Date4": '2019-12-22',
		"Date5": '2019/12/22 11:11:11'}
dumped = yaml.dump(dict, default_flow_style = False)
print(dumped)
```
results to:
```
Date1: '2019-12-22 11:11:11'
Date2: 2019-12-22 11:11.11
Date3: '11:11:11'
Date4: '2019-12-22'
Date5: 2019/12/22 11:11:11
```
Even just a 4 digit string results in extra single quotes.

edit @perlpunk fix code markers

**Comment by perlpunk** [comment]
That works like expected. A scalar constisting of digits like `2019` in YAML will be loaded as an integer. A scalar like `2019-12-22 11:11:1` will be loaded as a datetime object.
If you feed it to `dump` as strings, then YAML is supposed to keep it as strings, so it has to add quotes around it. Otherwise you would get back different data when loading it again.
