### ISSUE TITLE
5.1.2 released on pypi without first having a tag on github

### ISSUE THREAD

**Issue by ssbarnea** [yaml/pyyaml#325]
It seems that version 5.1.2 popped up today on https://pypi.org/project/PyYAML/ but there is not git tag present, not a release file on github.

This should count as a security issue as it could also be result of having the PYPI account hacked.

PYPI and github relases should be done only by the CI system once the tag is created (or pushed), the the other way around.

**Comment by nitzmahone** [comment]
Nah, just an oversight- because of the multi-platform builds and everything, the final parts of the release process are still very manual; I just forgot to push the tag after everything else was finished (following Ansible's current release management behavior that tagging is the *last* thing, not the first).

The irony isn't lost on me as a maintainer of Ansible that the release process isn't fully automated (eg, "the shoemaker's son goes barefoot" and all). We'll get there eventually.

**Comment by ssbarnea** [comment]
Indeed for multiplatform is much more complex, especially with Travis which does not have any artifact storage. On the other hand I plan to switch few projects I maintain from travis to azure-devops, as it has artifact support and much better conditions.
