### ISSUE TITLE
copy.deepcopy() with datetime objects fails with "TypeError: __init__() takes exactly 2 arguments (1 given)"

### ISSUE THREAD

**Issue by ralt** [yaml/pyyaml#387]
Apparently since this commit: https://github.com/yaml/pyyaml/commit/96d65f3de147cac6d500f8047b5542ff98a53884

**Comment by ralt** [comment]
Sorry, I did this ticket a bit too hastily. Here is a reproducer:

```
import copy
import datetime
import yaml

copy.deepcopy(yaml.constructor.timezone(datetime.timedelta(seconds=0)))
```
```
[ralt@tag ~]$ python2 /tmp/r.py
Traceback (most recent call last):
  File "/tmp/r.py", line 6, in <module>
    copy.deepcopy(yaml.constructor.timezone(datetime.timedelta(seconds=0)))
  File "/usr/lib64/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib64/python2.7/copy.py", line 329, in _reconstruct
    y = callable(*args)
TypeError: __init__() takes exactly 2 arguments (1 given)
```

It is when dealing with datetime objects.

**Comment by cognifloyd** [comment]
This only applies to python2. In python3, it uses the stdlib timezone objects.

So the minimal timezone object needs `__copy__` and `__deepcopy__` methods.

**Comment by cognifloyd** [comment]
Just to add a slightly more verbose description of this issue:
This bug occurs in python 2 + pyyaml 5.3+ when:

1. parse a document with a yaml timestamp
2. pyyaml converts that timestamp to a timezone aware datetime object where tzinfo is an instance of `yaml.constructor.timezone`
3. use `copy.deepcopy` to copy the python object (typically a dict) that resulted from parsing the yaml
4. `copy.deepcopy` fails miserably with the TypeError as described above because it can't copy `yaml.constructor.timezone`.

**Comment by ralt** [comment]
Thank you, you are much better at summarizing usefully the state of things :)

As of right now, we have reverted pyyaml to older than 5.3. Should we implement those methods or do you plan on fixing it in pyyaml?

**Comment by cognifloyd** [comment]
This broke one of my transient dependencies, and pyyaml is a transient dep of yet another transient dep... I don't have resources to fix it right now so I also pinned py2.7 to pyyaml <5.3.

But pyyaml is the proper place to fix this instead of pinning transient deps.

**Comment by ingydotnet** [comment]
If someone wants to submit a PR (extra credit if it has tests) I can get this out soon.

**Comment by ralt** [comment]
@ingydotnet [there you go](https://github.com/yaml/pyyaml/pull/392)

**Comment by ingydotnet** [comment]
thanks
