### ISSUE TITLE
yaml anchors are ignored

### ISSUE THREAD

**Issue by BardiaAfshin** [yaml/pyyaml#405]
when loading a yaml with anchors ie

input.yaml
`base: &base
  name: Everyone has same name`

code:
`with open(test_file, mode="r", encoding='utf-8') as t:
    contents = t.read()
    ci = yaml.safe_load(contents)`

output in console

`{'base': {'name': 'Everyone has same name'}}`

and when written out

code:
`cwd=Path.cwd()
... outfile = f"{cwd}/output.yaml"
... with open("output.yaml", mode="w", newline='') as file:
...     yaml.dump(ci, file)`

output.yaml
`base:
  name: Everyone has same name
`

observe: the anchor **&base** is not in the output file, or console output

sample anchor is taken from here -> https://learnxinyminutes.com/docs/yaml/

**Comment by perlpunk** [comment]
Your input.yaml
```
base: &base name: Everyone has same name
```
is invalid.

**Comment by perlpunk** [comment]
YAML anchors/aliases are a representation detail that is not supposed to be part of the loaded data.
There are YAML libraries (e.g. ruamel.yaml) that support this by storing additional information in the loaded data, but PyYAML does not do this currently.
Additionally, anchors that are not used as aliases, won't get an anchor on output, because they are only used once.
And additionally to that, because the way python works, anchors on scalars can't roundtrip, only on dictionaries and lists. Again, we would have to store additional information to be able to roundtrip.

**Comment by BardiaAfshin** [comment]
that's interesting, I'll have to backtrace my steps with ruamel - but I wasn't able to see the anchors get retained there either.


Here's a case where the anchor is being retained (with PyYAML), but it does some sort of renaming behind the scene

YAML input:
````
.barbados:
  script: &barbados
    - |
      # ------------------------------------------------------------------------
   ```

output written to file:
```
.barbados:
  script: **&id001**
  - "# ------------------------------------------------------------------------\n\
 ```

observe the rename from barbados to id001. In this case, it's better than not retaining the anchor, but the renaming is undesired.

here's the system python version and PyYAML specs
```import os
os.system("python --version")
Python 3.6.8
0
os.system("python -m pip freeze | grep -i pyyaml")
PyYAML==5.30```

**Comment by perlpunk** [comment]
That's actually not a "renaming", but as the anchor information is completely lost when loading, it just numbers the anchors and adds the prefix "id".
