### ISSUE TITLE
newlines inserted after loading yaml

### ISSUE THREAD

**Issue by BardiaAfshin** [yaml/pyyaml#406]
after loading yaml 

```
.yay:
  script: &yay
    - |
      # ------------------------------------------------------------------------
      echo "yay is here"
```

via code

```
with open(test_file, mode="r", encoding='utf-8') as t:
    contents = t.read()
    ci = yaml.safe_load(contents)
```

I get the following

```
pprint(ci.get('.yay'))
{'script': ['# '
            '------------------------------------------------------------------------\n'
            'echo "yay is here"\n']}
```

notice the newline that is inserted,
'echo "yay is here"**\n'**]}

 this is undesired

**Comment by perlpunk** [comment]
That's not a bug.
You get a linebreak, because that's what the literal block scalar does.
If you want to strip the last linebreak, use the chomp indicator:
```
literal block: |-
  no final linebreak
```

For a quite complete documentation of YAML quoting see my article http://blogs.perl.org/users/tinita/2018/03/strings-in-yaml---to-quote-or-not-to-quote.html
