### ISSUE TITLE
PyYAML not using libyaml bindings on Raspberry Pi OS (Debian armv7)

### ISSUE THREAD

**Issue by geerlingguy** [yaml/pyyaml#445]
When I install PyYAML using `pip` on my Raspberry Pi, which already has `libyaml-dev` installed, PyYAML never runs the `Running setup.py install for pyyaml` step during install, and it ends up only supporting the (slow) built-in PyYAML parser.

This means, in my case, that Ansible runs 3x slower on the Pi than it should (see related: https://github.com/ansible/ansible/issues/72030).

Here's a log from my installation: https://pastebin.com/HsYZMQ8m

If I run the exact same commands on a Debian 10 instance running on AMD64 hardware, I get:

```
# sudo pip3 uninstall pyyaml
Uninstalling PyYAML-5.3.1:
  Would remove:
    /usr/local/lib/python3.7/dist-packages/PyYAML-5.3.1.dist-info/*
    /usr/local/lib/python3.7/dist-packages/yaml/*
Proceed (y/n)? y
  Successfully uninstalled PyYAML-5.3.1
root@f2e5507476ec:/# sudo pip3 install --no-cache-dir pyyaml
Collecting pyyaml
  Downloading https://files.pythonhosted.org/packages/64/c2/b80047c7ac2478f9501676c988a5411ed5572f35d1beff9cae07d321512c/PyYAML-5.3.1.tar.gz (269kB)
    100% |████████████████████████████████| 276kB 6.6MB/s 
Installing collected packages: pyyaml
  Running setup.py install for pyyaml ... done
Successfully installed pyyaml-5.3.1
```

But that section about `Running setup.py install for pyyaml ... done` never appears on the arm version. Is there something blocking `setup.py` from running on arm distributions?

**Comment by nitzmahone** [comment]
This actually looks like a piwheels problem off the top of my head, since they're providing what's ostensibly an arch-specific wheel, but they're not building and including the libyaml extension bits (at least as of this writing). So if you add `--no-binary pyyaml` to your pip invocation, that should force it to build locally. Assuming you have all the necessary bits to build the extension on your pi, that should solve it.

A better thing might be to request piwheels to actually include the extension or stop publishing their wheels, because they're not really saving much over the sdist, and it's preventing a proper wheel with the extension from being built without folks specifically having to exclude their wheel.

**Comment by geerlingguy** [comment]
All right, so I've now tried the following:

```
$ sudo pip3 uninstall pyyaml
$ sudo pip3 install --no-cache-dir --no-binary pyyaml pyyaml
```

And what do you know, it looks like it's worked! It ran `setup.py install` and the libyaml support was added correctly.

It _seems_ that there may already be an issue for it here: https://github.com/piwheels/packages/issues/130

**Comment by nitzmahone** [comment]
Cool, since this isn't a pyyaml specific issue, I'll go ahead and close this one (and maybe go drop a couple hints on how to do an extension wheel build on that piwheels issue)
