### ISSUE TITLE
Adding Support for AIOFiles

### ISSUE THREAD

**Issue by SZanko** [yaml/pyyaml#448]
It would be nice to provide support for reading Yaml files in a async way.
Currently if you are trying to read a File with Aiofiles and Pyyaml with:

```
#!/usr/bin/python 
import asyncio 
import yaml 
import aiofiles 
async def testYamlRead(): 
    async with aiofiles.open('examplefile', mode='r') as f: 
        contents = await yaml.load(f,Loader=yaml.FullLoader) 
        return contents 
if __name__ =="__main__": 
    print(asyncio.run(testYamlRead())) 
```
You are getting this exeption:

```
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    print(asyncio.run(testYamlRead()))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "test.py", line 9, in testYamlRead
    contents = await yaml.load(f,Loader=yaml.FullLoader)
  File "/usr/lib/python3.8/site-packages/yaml/__init__.py", line 112, in load
    loader = Loader(stream)
  File "/usr/lib/python3.8/site-packages/yaml/loader.py", line 24, in __init__
    Reader.__init__(self, stream)
  File "/usr/lib/python3.8/site-packages/yaml/reader.py", line 85, in __init__
    self.determine_encoding()
  File "/usr/lib/python3.8/site-packages/yaml/reader.py", line 124, in determine_encoding
    self.update_raw()
  File "/usr/lib/python3.8/site-packages/yaml/reader.py", line 183, in update_raw
    self.stream_pointer += len(data)
TypeError: object of type 'generator' has no len()
```

Dependencies Versions:
Python Version: 3.8.6
Pyyaml Version:  5.3.1
aiofiles Version: 0.5.0
OS Arch Linux

**Comment by nitzmahone** [comment]
Short answer: this probably isn't going to happen.

Longer answer: doing this properly would require rewriting most of PyYAML's front-end APIs to be natively async, and for worse performance, at least in the case of `aiofiles`, since it's just doing threadpool-chopped sync IO to simulate async (for actual async file IO, see https://github.com/mosquito/aiofile). The only other way to do this would be to somehow detect a "fake" FP internally and consume it synchronously, since the fake FP provided by aiofiles doesn't implement normal FP semantics for consumption by standard Python (which is why it's breaking), much less C libs (eg, there's no way the `libyaml`-backed `CParser` would be able to consume it). This would preclude usage of the streaming parser for large YAML files. Basically, I can't think of any reason to support this where the solution isn't worse than the current problem of needing to pre-consume fake FPs (for small documents) or provide "real" FPs to PyYAML (for larger documents).

Given the scope of changes required to make this happen properly, I'm just going to close this one.
