### ISSUE TITLE
Python 3.6 wheels

### ISSUE THREAD

**Issue by graingert** [yaml/pyyaml#49]

**Comment by mcherm** [comment]
Help! How is this not resolved since February?

**Comment by graingert** [comment]
Presumably because wheels are complicated for compiled python libraries and that this is a volunteer run project?

**Comment by mcherm** [comment]
Oh sorry, no offense intended. It's not that I mean to demand things from a volunteer team, but just that I was surprised. First, I didn't realize that wheel files were difficult to generate (I don't know much about packaging). And second, it seems like it would have a big impact as it means anyone using the latest Python cannot install from PyPi (or at least that was the symptom I had).

I did get past the problem by checking out the source and building myself. The C build failed (due to my system surely) but it fell back to the pure Python implementation which meets my needs.

Thanks!

**Comment by partounian** [comment]
How can I help make this happen?

**Comment by samuelcolvin** [comment]
+1 for this it would be great.

For clarity, not sure why @mcherm was having problems install from pypi, normal install with `pip install pyyaml` works fine on 3.6, however the `libyaml` c build doesn't occur without the wheel AFAIK.

https://github.com/joerick/cibuildwheel give instructions on building wheels using CI, surely that would be the way to do?

Associated question: is where a way to get the `libyaml` c extension to build when installing from pip, eg. a package i need to installed?

I'm on ubuntu and already tried installing `libyaml-dev` and `libyaml-0-2`.

**Comment by ingydotnet** [comment]
PyYAML-3.13 is out and we can build wheels properly now for all relevant python versions.

Big thanks to @nitzmahone !!
