### ISSUE TITLE
pyyaml package upgrade issue

### ISSUE THREAD

**Issue by Dexter706** [yaml/pyyaml#501]
environment:Ubuntu-18.04
Hi,
I am trying to update the **pyyaml** package for python 3.6.9 to the latest ver 5.4 by using the cmd "sudo pip install PyYAML".
Having both python versions 2.7.4 and 3.6.9 on my system. By default, pyyaml is getting upgraded for the python version 2.7.4.
There is no option to upgrade the 'pyyaml' for python 3.6.x ver. How to upgrade the 'pyyaml' for python 3.6.x if python 2.7.x version is also there.
Regards,
Sumit

**Comment by dabrowne** [comment]
You most likely need to use the `pip3` executable, not `pip`. Furthermore it is considered bad practice to `pip install` with `sudo`, which will install the package globally on your machine. Ideally you would be working within a Python virtualenv, otherwise you can install using `--user` to install in your user home directory, which does not require root privileges:

```
pip3 install --user PyYAML
```

**Comment by nitzmahone** [comment]
This is a distro Python config thing, not a pyyaml issue, so we'll be closing it... That said, the better way is to invoke pip as a module from the Python you know you want to install it under. So if you're using `/usr/bin/python3` (and it's got a pip), do `/usr/bin/python3 -m pip install pyyaml`. Otherwise you're still at the mercy of whatever `pip` or `pip3` gets found on your `PATH`.
