### ISSUE TITLE
Arm64 build not found for version 5.4.1

### ISSUE THREAD

**Issue by GO3LIN** [yaml/pyyaml#552]
While using PyYaml 5.4.1, and building for arm64, the pip install fails because there's no arm64 version in the wheel. And by checking the available versions, there is an aarch64 version that may be used. That also directed me to knowing that arm64 == aarch64, but why pip doesn't consider them equal ? should I just target aarch64 or there's another thing I missed ? thank you in advance !

**Comment by nitzmahone** [comment]
Python generally uses `aarch64` as a synonym for arm64 in platform tags etc. `pip` will only select wheels that are apropos for your platform, ABI, and Python version (which you didn't share, so I can't tell you anything more specific). Many Linux flavors, MacOS and Windows all run under aarch64, but we currently only publish arm64/aarch64 wheels for manylinux (glibc) on Python 3.6-3.9. We'll be adding MacOS 11 aarch64 wheels soon, as well as Python 3.10 wheels for all supported arches, but otherwise, if you want the libyaml extension, you'll have to ensure that you've got Cython, the proper dev tools, and libyaml + headers available on whatever you're trying to build for so it can auto-build from the sdist. If you want the pyyaml build to fail when the extension can't be built (instead of falling back to the slow pure-Python mode), you can set `PYYAML_FORCE_CYTHON=1` and `PYYAML_FORCE_LIBYAML=1` before invoking `pip install`.

Closing this for now, but let us know if anything's not clear there.
