### ISSUE TITLE
ERROR: PyYAML-6.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by joefh** [yaml/pyyaml#585]
We have been using the following command to install python in our container:
```
RUN pip3 install -U pip && \
    pip install wheel && \
    pip wheel -w /tmp/wheels
```
It's been working fine, until we hit the following error:

ERROR: PyYAML-6.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl is not a supported wheel on this platform.

Would someone please let us know how to solve this?

**Comment by nitzmahone** [comment]
Missing pretty much all the information needed to actually tell you what's going on, but that error (which I assume is coming from a `pip install` you aren't showing?) means you asked pip to install a wheel that doesn't match its Python version or wheel arch. If I had to guess, your `pip3` and `pip` invocations (why are you mixing them?) don't point at the Python you think they do, and they're mismatched with whatever Python version you're actually trying to install the resultant wheel in, or the pip in the Python you're installing to is so old it doesn't understand manylinux tags.

It's usually better to be specific about the path to the Python you're using and invoke its pip directly as a module, rather than hoping a `pip` script is in the proper place in your `PATH` to match with a future Python invocation. eg, `/usr/bin/python3.9 -m pip wheel` followed by `/usr/bin/python3.9 -m pip install (the wheel you just built)`.

In any case, without more information to the contrary, this sounds like an environment config issue...
