### ISSUE TITLE
 cannot import name 'CLoader' from 'yaml'

### ISSUE THREAD

**Issue by rlgn** [yaml/pyyaml#598]
I get the following error

ImportError: cannot import name 'CLoader' from 'yaml' /Users/home/.pyenv/versions/p3/lib/python3.8/site-packages/yaml/__init__.py

On an M1 Mac mini. Could this be an issue due to Apple Silicon?

**Comment by sanjay900** [comment]
I got this working by installing libyaml and then rebuilding
First, install homebrew, then
```
brew install libyaml
pip uninstall PyYaml
LDFLAGS="-L/opt/homebrew/lib/" CFLAGS="-I/opt/homebrew/Cellar/libyaml/0.2.5/include" pip install PyYaml
```

**Comment by nitzmahone** [comment]
If homebrew's involved, all bets are off on what you're going to get if you build PyYAML yourself on an arm64 host, because depending on how your paths are configured, the libyaml binary it finds might be Intel or arm64, but IIRC never a universal binary.

We ship MacOS arm64 wheels with a statically-linked libyaml included, but the CI and release tooling for Python 3.8 on Apple Silicon was largely busted when we added Apple Silicon support, so we only ship them on 3.9+. I'd strongly suggest using at least Python 3.9 if you're on Apple Silicon- it'll make your life much easier.
