### ISSUE TITLE
yaml.load not Class aware

### ISSUE THREAD

**Issue by gsal** [yaml/pyyaml#615]
As I added more and more features to my program and more attributes to my classes, I run into some issues that made me realize that yaml.load is just not aware of my class...is this correct? Meaning, it seems to be putting together an object purely based on the contents of the yaml file without first possibly going through my Class.__init__ and THEN populating the object. 

If so, how can I make happen? There is more to my object that just what I decided to write out to the yaml file. 

Otherwise, it seems that I would need to create (sub) classes/objects for the sole purpose of reading/writing to yaml.

Please adivse. 

Edit: if only one could pass the class or an already initialized object ?

**Comment by perlpunk** [comment]
Can you please add a minimal reproducing example code?

**Comment by nitzmahone** [comment]
Once again, you're not thinking like a serializer :wink: ...

Deserializers don't typically call instance initializers by default, as they don't know how to fill the initializer arguments in a generic way. Instead they create a "hollow" instance of the object (via `__new__`) and populate it directly with the information that was serialized. If you leave the default serialization behavior alone, you'll get a round-trippable object, but because you've customized the serialization with `__getstate__` to filter out internal attributes, you'll also have to customize the deserialization with a custom `__setstate__` to reconstruct those attributes outside of the instance initializer (which won't be called).

Since you're using YAMLObject, take a look at [the default implementation of `from_yaml`](https://github.com/yaml/pyyaml/blob/master/lib/yaml/__init__.py#L377-L381) and the [object constructor it calls](https://github.com/yaml/pyyaml/blob/master/lib/yaml/constructor.py#L416-L424). The generic deserializer will never call the object initializer, since it doesn't know the signature, args, or expected calling semantics. It just creates a hollow object with `__new__`. Since your object doesn't define a setstate method, it's just plopping the dictionary it deserialized for that object in as its `__dict__`, which gives you only the attrs that were represented in the serialized YAML (of your own making). So you can either provide a customized `__setstate__` that does all the work, make your `other_init` attribute into a lazy property that gets initialized on first read, or customize your object's `__new__` to set `other_init`.

**Comment by gsal** [comment]
I mean, it makes sense and, sure, thing are working as designed given what I am doing, the question remains...what in the world am I to do to make it work?  The above description continues to be rather obscure in regards to the actual implementation. 

Will it be too much to ask you or somebody else to answer in-kind and show some code? Make the fixes to my minimal program above?  I still don't know what yaml calls to make, even if I manage to put together some minimal `__getstate__`.

The literature regarding `__setstate__` and `__getstate__` is rather brief and pickle oriented.

**Comment by nitzmahone** [comment]
OK, last one:
```
    def __setstate__(self, d):
        self.__dict__.update(d)
        self.other_init = 'initialized'
```
