### ISSUE TITLE
yaml/_yaml.c is missing even from pypi source tarballs, can't build C extension

### ISSUE THREAD

**Issue by karolyi** [yaml/pyyaml#616]
Hey,

I've tried to reach out to people on IRC but to no avail.

I'm trying to compile a FreeBSD C extension so that parsing/loading would be faster.

The github tarball doesn't contain `yaml/_yaml.c`. According to #385, github is only the secondary source. I can live with that.

But when going to pypi and downloading the tarball (currently [
PyYAML-6.0.tar.gz](https://files.pythonhosted.org/packages/36/2b/61d51a2c4f25ef062ae3f74576b01638bebad5e045f747ff12643df63844/PyYAML-6.0.tar.gz)), that tarball doesn't have the aforementioned file either.

Added to that, the site itself is kinda outdated, and everything points to github: the pypi links, and the links on the website too.

With that, I'm kinda lost.

Where should I get the source now? Where is the primary git remote?

**Comment by nitzmahone** [comment]
Docs and website aren't my area, but it sounds like you're trying to build the extension manually, which is ... not a great idea.

Short answer: Just let the Python infra build it for you. Assuming you want a wheel and not just a local install:
```
sudo pkg install -y python38 libyaml && PYYAML_FORCE_LIBYAML=1 python3.8 -m pip wheel pyyaml==6.0
```

The envvar isn't required, but it'll force an error and prevent it from silently falling back to a pure Python build if there's a problem with the extension build.

Since declarative build deps became workable when we adopted PEP517/pyproject.toml ~pyyaml 5.x, and after getting burned a few times with stale generated Cython code breaking on newer Pythons, we stopped shipping intermediate sdists with those files embedded and just made Cython required for the build. This doesn't affect most users on platforms where we also started shipping wheels, but as I'm sure you're well aware, FreeBSD isn't supported by PyPI for pre-built wheels, so y'all are on your own.

Closing as "as designed".

**Comment by karolyi** [comment]
This doesn't really help.

I can understand why you don't want to bundle the `yaml/_yaml.c` file, but the build on FreeBSD still fails unless you don't provide `C_INCLUDE_PATH=/usr/local/include/` in front of the commandline you've given for building the C extension.

The error output for building the wheel was:
```
PYYAML_FORCE_LIBYAML=1 python -m pip wheel pyyaml==6.0
Collecting pyyaml==6.0
  Using cached PyYAML-6.0.tar.gz (124 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: pyyaml
  Building wheel for pyyaml (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for pyyaml (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      running bdist_wheel
      running build
      running build_py
      running build_ext
      skipping 'yaml/_yaml.c' Cython extension (up-to-date)
      building 'yaml._yaml' extension
      In file included from yaml/_yaml.c:679:
      yaml/_yaml.h:2:10: fatal error: 'yaml.h' file not found
      #include <yaml.h>
               ^~~~~~~~
      1 error generated.
      error: command '/usr/bin/cc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyyaml
Failed to build pyyaml
ERROR: Failed to build one or more wheels
```

It would be beneficial to add that in case of *BSDs, since the default include path isn't `/usr/include` but `/usr/local/include`, since `${prefix}` is `/usr/local`.

Please don't close issues without investigating them any further. This isn't an issue without substance. The problem was, building the wheel and trying to install the package provided two different error messages, hence the original issue message I opened.

The end goal is to have a C extension availability on *BSDs too.

**Comment by nitzmahone** [comment]
I went to the trouble of firing up a FreeBSD 13.0 instance on AWS and trying the command that I gave you- I thought that was pretty above and beyond as it was. Don't worry, I won't make that mistake again.

We're not overriding include locations, so if your Python isn't picking them up, you clearly knew what to do to get it to do so. Feel free to open a separate issue about the docs, but I've explained why we're doing it this way, and provided a way to make it work.
