### ISSUE TITLE
OrderdDict returned to python

### ISSUE THREAD

**Issue by c-w-m** [yaml/pyyaml#623]
Can an OrderdDict be used as the return dictionary to python?

**Comment by c-w-m** [comment]
Just expose the option for more recent python versions.  Sorry, I'm being narrow minded about the total package user base. ;-)

**Comment by nitzmahone** [comment]
Since order-preserving dictionaries are the default behavior on all versions of Python that PyYAML currently supports, this is sort of a non-issue. If you want to change the default mapping type that gets constructed to `OrderedDict`, you can do so with some judicious subclassing of various Loader bits, but I'll leave that as an exercise for the reader..

Closing the request, as it's not something we're likely to implement in the base library classes, and it can be done by a determined subclasser.
