### ISSUE TITLE
pathlib object cannot be loaded

### ISSUE THREAD

**Issue by vascotenner** [yaml/pyyaml#665]
pathlib is a python module shipped in the python core package.  When trying to save and load a WindowsPath object, I encountered the following issue:

**Issue** Code:
```python
from pathlib import WindowsPath
import yaml

WindowsPath('C:/')
with open(target, 'w') as file:
    yaml.dump(d, file)
# There is a bug in yaml + windowspath: it cannot load it.
with open(target, 'r') as file:
    d3 = yaml.full_load(file)
```
**Error**:
```python
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/object/apply:pathlib.WindowsPath'
  in "C:\Users\user\AppData\Local\Temp\tmpo3a1m6g1\test.yml", line 1, column 1
```

**Expected behavior**: Hence I expect that pyyaml can seamlessly save and load python object types that are in the core python distribution.

**Workaround**: A solution was mentioned in #617: save the path as a string explicitly. However, this has the drawback that the object is load as a string instead of a Path.
```python
from pathlib import WindowsPath, PurePath
import yaml

def path_representer(dumper, data):
      return dumper.represent_scalar(u'tag:yaml.org,2002:str', str(data))

yaml.add_multi_representer(PurePath, path_representer)

WindowsPath('C:/')
with open(target, 'w') as file:
    yaml.dump(d, file)

with open(target, 'r') as file:
    d3 = yaml.full_load(file)
```

**Comment by nitzmahone** [comment]
You need the `UnsafeLoader` to allow import of arbitrary Python modules:
```
>>> yaml.load('!!python/object/apply:pathlib.WindowsPath\n- c:\\\n- dude\n', Loader=yaml.UnsafeLoader) 
WindowsPath('c:/dude') 
```
(`FullLoader` lets you construct types whose modules have already been imported, but won't import new types, `UnsafeLoader` does the same, but will blindly import the named module if it's not already there)

But I'd also suggest that unless your documents are only ever being deserialized on Windows hosts that you consider serializing those to strings (as mentioned above) or at least `pathlib.Path` instead of letting the bare `pathlib.WindowsPath` through, since if you try to deserialize that on a non-Windows host, the `WindowsPath` construction will fail:
```
>>> yaml.load('!!python/object/apply:pathlib.WindowsPath\n- c:\\\n- dude\n', Loader=yaml.UnsafeLoader) 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
...
NotImplementedError: cannot instantiate 'WindowsPath' on your system
```

Anyway, closing this as "as-designed".

**Comment by tlhr** [comment]
Reopening this because I'm not seeing the behavior mentioned in the comment. The following fails for me in PyYAML 6.0.1:

```python
import pathlib
import yaml

file = "test.yaml"
with open(file, "w") as f:
    yaml.dump(pathlib.Path("./"), f)

# Works
with open(file, "r") as f:
    print(yaml.load(f, Loader=yaml.UnsafeLoader))

# Crashes
with open(file, "r") as f:
    print(yaml.load(f, Loader=yaml.FullLoader))
```

Note that `pathlib` has already been imported.
