### ISSUE TITLE
Linking against libyaml fails with python 3.11

### ISSUE THREAD

**Issue by bneumeier** [yaml/pyyaml#690]
When installing with `--with-libyaml` on python 3.11, compilation fails because the location of a header file has changed:

ext/_yaml.c:196:12: fatal error: longintrepr.h: No such file or directory

A conditional block based on the python version might help?

**Comment by nitzmahone** [comment]
That code is all generated on the fly by Cython. We've been building with the libyaml extension against 3.11 for over a year on numerous platforms with no issues. At a glance, I'd suspect that your Cythonized source is stale, or that you've got something else going on with your target environment. Also, I'd suggest using [build](https://pypi.org/project/build/) or something instead of manually invoking `setup.py ` as we'll likely be ripping out all the legacy customized distutils command stuff from `setup.py`, since Cython is dropping support for the extension points we're using.

**Comment by nitzmahone** [comment]
It *does* work properly today, but an upcoming (as yet unreleased) version of Cython will break it in an incompatible way. We added support for PEP517 builds quite awhile ago, so I'm suggesting you start using it before we remove the setup.py support when Cython breaks it.

**Comment by nitzmahone** [comment]
PyYAML builds successfully thousands of times a day on numerous Linux distros against Python 3.11- the error you're seeing is usually attributed to stale Cythonized sources that were built by an old Cython. If you use the PEP517 build with proper build isolation, it'll ensure that you've got a working Cython and re-Cythonize the sources for you. Invoking setup.py manually will do none of that.

**Comment by bradfordboyle** [comment]
I know this issue is closed, but I recently ran into this issue with PyYAML 5.3.1 and I wanted to shared a work-around that worked for me in case anyone else gets tripped up on this.

If I download the [source distribution from PyPI](https://pypi.org/project/PyYAML/5.3.1/#files), it includes the generated C source (i.e., `ext/_yaml.c`) already; if I download the [source code from GitHub](https://github.com/yaml/pyyaml/releases/tag/5.3.1), it does not include the generated C source. Looking at [`setup.py`](https://github.com/yaml/pyyaml/blob/5.3.1/setup.py#L78-L81), it sets `with_cython` to be true when building a source distribution, so this is to be expected. For my use case, I was able to simply remove `ext/_yaml.c` before running `python3 setup.py build`. You will need to have the `Cython` module installed -- on Debian this is provided by the `cython3` package.
