### ISSUE TITLE
drop of "requires" and "properties" attributes during load

### ISSUE THREAD

**Issue by freegroup** [yaml/pyyaml#706]
For some reason, the lib does not read properties/attributes which are named `requires` or `properties`. They are dropped silently. Is it possible to avoid this or just report an error if some attributes can't be read?

the part on the left is after writing the YAML. The `requires` attribute is dropped (and all `properties` attributes as well)

<img width="1453" alt="image" src="https://user-images.githubusercontent.com/1155039/225631216-a2517dd9-e930-446f-9300-5e18e4953016.png">

**Comment by perlpunk** [comment]
If pyyaml would just drop any key called "requires" or "properties", I assume many more people wold have complained already.

In other words, if you really think this is a bug in pyyaml, please add a small, complete, reproducing code example that shows this behaviour and can be executed by one of us.
Otherwise noone is able to help, and this will be closed.
