### ISSUE TITLE
Compatibility of PyYAML with Python 3.11.2

### ISSUE THREAD

**Issue by kmaheshwari-splunk** [yaml/pyyaml#707]
Hi folks,

The [Pypi documentation](https://pypi.org/project/PyYAML/) mentions that PyYAML v6.0 is compatible with Python >= 3.6.
Does this claim that the library is compatible with Python 3.11.x as well?
If not, is there a plan to release a Python 3.11.x compatible version?

**Comment by nitzmahone** [comment]
Yes, 3.11 is fully supported, and has been since it hit beta. Since 3.11 support didn't require a new release, we just added 3.11 wheels for our supported platforms under the existing 6.0 release. The PyPI trove metadata can't be updated to explicitly show 3.11 support until we actually need to do a new release, but note the 3.11 wheels at https://pypi.org/project/PyYAML/#files

**Comment by kmaheshwari-splunk** [comment]
Thanks for the information!
