### ISSUE TITLE
Line with extra spaces causes style changes. Bug or Feature?

### ISSUE THREAD

**Issue by d3cryptofc** [yaml/pyyaml#712]
**Versions**
Python 3.11.3
PyYAML 6.0

**Parameters**
Default Style: |
Allow Unicode: True

#### Input (contains extra spaces on line 3)
```yaml
description: |
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam non porta urna. Cras vel mi accumsan, 
    
  pulvinar urna vitae, rutrum quam.
```

#### Wrong output
```yaml
"description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam non\
  \ porta urna. Cras vel mi accumsan, \n  \npulvinar urna vitae, rutrum quam."
```

#### Expected output
```yaml
"description": |-
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam non porta urna. Cras vel mi accumsan,

  pulvinar urna vitae, rutrum quam.
```

#### Code

```python
with open('input.yml', 'r') as file:
    data = yaml.safe_load(file)

with open('output.yml', 'w') as file:
    print(yaml.safe_dump(data, file, allow_unicode=True, default_style='|'))
```

#### Solution
Solved it for me by removing extra spaces in the YAML file.

**Comment by nitzmahone** [comment]
This appears to be working as-designed: https://github.com/yaml/pyyaml/blob/6.0.1/lib/yaml/emitter.py#L759-L763 - basically the embedded spaces followed by a break are explicitly disallowed in block scalars by the emitter. It is curious that the parsers preserve it properly in a block scalar though- maybe something that was tightened up in later versions of the spec but the emitter code didn't evolve accordingly? That'd probably be an @ingydotnet question (or someone else more involved in the spec minuatiae).

Meantime, I'm going to close the issue for now, since the emitter code does seem to be designed to explicitly prevent this case.

**Comment by perlpunk** [comment]
It's valid YAML. Just that it was decided in PyYAML to disallow this even when literal style is explicitly requested by the user, and there are different opinions on whether it should or that or not.
There's an issue for that: #121

**Comment by nitzmahone** [comment]
Thanks @perlpunk for the issue necromancy- I've added #121 to the 6.1 planning project. I'm willing to do a little work to try any get this behaving, as well as getting the full YAML test suite integrated (since we're going to want that for a bunch of the other things we're talking about anyway ;) )
