### ISSUE TITLE
Unable to install due to dependency on setuptools - help please?

### ISSUE THREAD

**Issue by agaldran** [yaml/pyyaml#786]
Hello,

Sorry if I am asking silly questions but I am new at this and a bit desperate to make things work. I need to install in a remote platform a machine learning library (https://pypi.org/project/tabpfn/), I am allowed to upload files but I do not have access to the internet there. I downloaded the file `tabpfn-0.1.10-py3-none-any.whl` and dropped it into the platform. Now, when I run:
```
pip install --no-index .../tabpfn-0.1.10-py3-none-any.whl
```
I get an error saying that pyyaml is required. I then upload a version of pyyaml that complies with the requiremet (>= 5.4.1) and I get a complain about setuptools being missing. I upload the latest version of setuptools (69.1.1) and install it before trying to install pyyaml, and now, even if I can see that setuptools has been successfully installed, it does not help to install pyyaml, I am attaching the successive screenshots.

I am actually not a bit but quite desperate here. I have tried many random combinations of setuptools and pyyaml versions (5.4.1, 5.4.b2, 6.0, 6.0b1, 6.01 in conjunction with setuptools 69.1.1, 67.8.0, and 65.7.0), but none seem to work for me, and I am no expert in software dependencies (just a poor mathematician). If any soul here can give me some clue on what to try next - in as much un-assuming terms as possible - I will deeply appreciate it.

Cheers,

Adrian

![image](https://github.com/yaml/pyyaml/assets/4498444/bd609ba7-83f2-4e39-badf-b9749445e8a0)

![image](https://github.com/yaml/pyyaml/assets/4498444/20fe6ec4-5b16-4480-b5b6-a29ad8fa18e8)

![image](https://github.com/yaml/pyyaml/assets/4498444/3f3eec86-35f6-4de9-ac8b-11102c01ba52)

**Comment by nitzmahone** [comment]
You're trying to install PyYAML from a source dist, which requires a build process of some sort to make it usable (handled by setuptools). Since you're already installing wheels (built distributions) for other things, why not just grab a [PyYAML wheel] for your platform (https://pypi.org/project/PyYAML/#files) too? Then you don't need to build it, so you don't need setuptools.

If you want to make the build work, you'll need to get all the right compilers/headers/libs for libyaml installed, then you probably want to do a `--no-build-isolation` (which tries to create an isolated build environment and install the build dependencies from an index you can't reach), or do that on some other host that *can* reach the internet and use `pip wheel` or `build` to give you a wheel that will work in your target env.

**Comment by agaldran** [comment]
Hi Matt!

Thanks a lot for the pointer, it turns out that a wheel solved the issue, and also I learned the difference between building from source (which requires that damned setuptools thing) and using a compiled wheels file, amazing!

Thanks very much for the super-fast answer, really appreciated, seriously. The open-source community is a gift to humanity :)
