### ISSUE TITLE
Python 3.13 support

### ISSUE THREAD

**Issue by nitzmahone** [yaml/pyyaml#797]
Now that Python 3.13.0b1 is out, time to get at least a 6.0.2 pre-release out the door with 3.13 support. Most everything is working, but there are a couple of deferred housekeeping things that I'm still finishing up...

- [x] Support for Cython 3.0+ (via conditional `old_build_ext` import)
- [x] Custom `cibuildwheel` with 3.13 support
- [ ] Update CI.yaml to use dynamic matrix (eliminate extra copy for release)
- [ ] Support for `macos-14` GHA runner (native Apple Silicon, reduces need for our self-hosted runners)
- [ ] Update libyaml Mac shared build to work with newer autoconf
- [ ] Support for `windows-2022` GHA runner
- [ ] Update libyaml Windows shared build to run under VS2022

**Comment by Uzume** [comment]
In regard to "Support for Cython 3.0+ (via conditional `old_build_ext` import)", is a #731/#602 style "fix" (to get around cython/cython#4498) really a good idea? Wouldn't it be a better idea to move away from `cython_sources`, `Cython.Distutils.build_ext`/`Cython.Distutils.old_build_ext` and the deprecated [`distutils`](https://github.com/pypa/distutils) to the supported `Cython.Build.build_ext`? Cython likely means to drop support for those deprecated interfaces at some point (especially since python/cpython#92584). Wouldn't a #729 style fix (at build time only; see my comments there) be a better approach since [Distributing Cython modules](https://docs.cython.org/en/latest/src/userguide/source_files_and_compilation.html#distributing-cython-modules) seems to be the recommended and supported method (and presumably is more unlikely to break in the future)?
