### ISSUE TITLE
"on: true" gets parsed as "True: True" when using safe_load

### ISSUE THREAD

**Issue by y2k0999** [yaml/pyyaml#807]
os: ubuntu 22.04
arch: x86_64
python version: 3.10.12
![Screenshot from 2024-06-06 13-33-45](https://github.com/yaml/pyyaml/assets/152584823/265931dc-4d40-4a76-ae9f-8a576beaf90d)

**Comment by perlpunk** [comment]
There is a [pinned issue](https://github.com/yaml/pyyaml/issues/486) that you should see when you go to https://github.com/yaml/pyyaml/issues
Also there are multiple issues mentioning `on` and `True`. Please search existing issues before creating new ones and try to make sure you are actually reporting a bug.
PyYAML implements YAML 1.1 currently. In YAML 1.1 `on` is a boolean.

Try [yamlcore](https://pypi.org/project/yamlcore/) on top of PyYAML if you want to process YAML 1.2.

Also, don't use an image to show text without need.
You could have just copy-pasted that text here instead of making a screen shot. Think about visually impaired people. (And wasting resources)

**Comment by perlpunk** [comment]
Closing as duplicate

**Comment by y2k0999** [comment]
I am visually impaired, please be more sensitive
